# PAM test

In [1]:
import numpy as np
import scipy as sp
import sys
from sklearn.cluster import KMeans as sKMeans
from sklearn_extra.cluster import KMedoids
from math import atan2, cos, sin, sqrt
import matplotlib.pyplot as plt
from random import sample
import seaborn as sns

%matplotlib inline
%load_ext autoreload

In [2]:
sys.path.append("/home/gmancini/Dropbox/appunti/Clustering/src")
import mdutils
import myclusters
import myvalidation
%autoreload 2

use distance of cities in the U. S. as reference dataset; convert coordinates to distances.

In [3]:
def distance(coord0,coord1,radius=6373.0):
    dlon = coord1[1] - coord0[1]
    dlat = coord1[0] - coord0[0]

    a = sin(dlat / 2)**2 + cos(coord0[0]) * cos(coord1[0]) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = radius * c

#### load data for US cities

In [4]:
import csv
ifile = open("places.txt")
places = csv.reader(ifile)
data = np.empty((300,2))
for i,city in enumerate(places):
    data[i] = city
nplaces = data.shape[0]
data.shape

(300, 2)

In [5]:
#convert to radians
coords = (np.pi/180.)*data

In [6]:
np.min(data[:,1]),np.max(data[:,1]),np.min(coords[:,1]),np.max(coords[:,1])

(33.429424, 43.5093982, 0.5834535158452129, 0.7593822541512942)

#### convert latitude / longitude to kilometric distances

In [7]:
distances = np.zeros((nplaces,nplaces))
for i in range(nplaces-1):
    for j in range(i+1,nplaces):
        distances[i,j] = distance(coords[i],coords[j])
        distances[j,i] = distances[i,j]

## settings

In [8]:
nclusters = 3
niter = 500
metric = 'cityblock'

In [9]:
data.shape

(300, 2)

In [10]:
np.argmin(data)

196

In [11]:
data[196],data[98,0]

(array([-112.06649  ,   33.4667869]), -112.0996404)

In [12]:
np.where(data==np.amin(data))[0]

array([98])

## PAM

In [13]:
my_estimator = myclusters.PAM(K=nclusters,niter=niter,metric=metric)
cost, medoids = my_estimator.do_clustering(X=data)
cost, medoids, my_estimator.nstep, my_estimator.nswap

([235, 133], 133, -1)
([235, 133, 61], 61, -1)
2.6831551e-316


(16627.11196, [235, 133, 61], 0, 0)

In [16]:
data[my_estimator.medoids]

array([[ -80.843784 ,   35.2275289],
       [-112.0737923,   33.4568607],
       [ -80.5243892,   43.4752375]])

In [14]:
my_estimator.clusters

array([133, 133, 133, 133,  61,  61, 235, 133, 133, 235, 133, 235,  61,
       133, 235, 235, 235, 133, 235,  61,  61,  61,  61, 235, 133,  61,
       133,  61, 133, 133,  61, 235, 133, 133, 133, 235,  61, 133,  61,
       235, 235, 235, 235, 235, 235,  61, 133, 235, 133, 133,  61, 235,
       133, 235,  61, 235, 133, 235,  61, 235, 133,  61, 235, 133,  61,
       235, 235, 133,  61, 235,  61, 133, 235,  61, 133, 133, 133, 235,
        61, 133, 133, 235, 133,  61, 133, 133,  61, 133,  61, 133,  61,
        61, 133,  61,  61,  61, 235, 235, 133, 133, 133,  61, 133, 133,
       235, 235, 133,  61, 133, 133,  61, 235, 133,  61, 133, 133,  61,
       133,  61,  61, 235, 235, 133,  61, 235,  61, 235,  61, 235,  61,
       235,  61, 235, 133, 133,  61,  61, 133, 133,  61, 235, 235, 133,
        61, 235, 235, 235, 133, 235, 235,  61, 235, 235,  61,  61,  61,
        61,  61, 235, 235,  61, 133,  61, 133, 235,  61,  61,  61,  61,
        61,  61, 133, 133, 235, 235, 133,  61, 235, 235,  61, 13